# Generated by Django 2.1.2 on 2018-10-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
