# Generated by Django 2.1.2 on 2018-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_perrito_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='fecha_ingreso',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
