# Generated by Django 2.1.2 on 2018-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_auto_20181126_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
