# Generated by Django 2.1.2 on 2018-10-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comuna',
            field=models.CharField(choices=[('Arica', 'Arica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='region',
            field=models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipovivienda',
            field=models.CharField(choices=[('Patio grande', 'Patio grande'), ('Patio pequeño', 'Patio pequeño'), ('Casa sin patio', 'Casa sin patio'), ('Departamento', 'Departamento')], max_length=30),
        ),
    ]
