# Generated by Django 2.1.2 on 2018-10-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181023_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comuna',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='region',
            field=models.CharField(max_length=30),
        ),
    ]
