# Generated by Django 2.1.2 on 2018-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181026_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='region',
            field=models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaiso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ("Libertador General Bernardo O'Higgins", "Libertador General Bernardo O'Higgins"), ('Maule', 'Maule'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aisén del General Carlos Ibáñez del Campo', 'Aisén del General Carlos Ibáñez del Campo'), ('Magallanes y de la Antártica Chilena', 'Magallanes y de la Antártica Chilena')], max_length=30),
        ),
    ]
